"""Build verified, size-bounded S2-COL-R2 data/report and source archives."""
from __future__ import annotations

import hashlib
import io
import json
import tarfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RUN = ROOT / "work/S2_COL_R2"
DELIVERY = ROOT / "deliveries/s2_col_r2_20260916"
LIMIT = 300_000_000
TAG = "20260916"

# Directories and files held back from the data archive. Every entry here is
# reported in OMITTED_ARTIFACTS.json with its on-disk size and the reason it
# could not travel inside the 300MB budget.
OMITTED_DIRS = {
    "FEATURES": "9.8GB reader feature cache; 108536 single-feature tensors, regenerated by the reader pass",
    "FEATURE_INDEX": "feature-hash to (query, target, evidence) index; rebuildable from FEATURES and JOBS",
}
OMITTED_FILES = {
    "NATURAL_TRAIN/natural_train_T0_pairs.sqlite": "960MB frozen T0 pair cache backing FROZEN_NATURAL_TRAIN.jsonl.gz",
}
OMITTED_SUFFIXES = {
    ".pt": "model checkpoint tensor; training history, feature identity and provenance hashes are included",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def safe(path: Path) -> Path:
    """Reject protected files and symlinks before packaging."""
    if ".env.openai" in path.parts or path.is_symlink():
        raise ValueError(f"protected or symbolic path cannot be packaged: {path}")
    resolved = path.resolve()
    if ".env.openai" in resolved.parts:
        raise ValueError(f"protected path cannot be packaged: {path}")
    return resolved


def copy_record(path: Path, archive_path: str) -> dict:
    path = safe(path)
    if not path.is_file():
        raise FileNotFoundError(path)
    stat = path.stat()
    record = {
        "archive_path": archive_path,
        "source_path": str(path),
        "bytes": stat.st_size,
        "sha256": sha256(path),
    }
    if path.stat().st_size != stat.st_size or path.stat().st_mtime_ns != stat.st_mtime_ns:
        raise ValueError(f"file changed during hashing: {path}")
    return record


def excluded(relative: Path) -> tuple[str, str] | None:
    """Return the (group, reason) holding a path out of the data archive."""
    if relative.parts and relative.parts[0] in OMITTED_DIRS:
        group = relative.parts[0]
        return group, OMITTED_DIRS[group]
    if relative.as_posix() in OMITTED_FILES:
        return relative.as_posix(), OMITTED_FILES[relative.as_posix()]
    if relative.suffix in OMITTED_SUFFIXES:
        return f"*{relative.suffix}", OMITTED_SUFFIXES[relative.suffix]
    return None


def data_records() -> tuple[list[dict], list[dict]]:
    """Walk the run tree, returning included records and aggregated omissions."""
    records: list[dict] = []
    omitted: dict[str, dict] = {}
    for path in sorted(RUN.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(RUN)
        held = excluded(relative)
        if held is None:
            records.append(copy_record(path, relative.as_posix()))
            continue
        group, reason = held
        entry = omitted.setdefault(group, {"relative_path": group, "bytes": 0, "files": 0, "reason": reason})
        entry["bytes"] += path.stat().st_size
        entry["files"] += 1
    if not records:
        raise ValueError("no data files selected for packaging")
    return records, sorted(omitted.values(), key=lambda entry: -entry["bytes"])


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def write_text(path: Path, text: str) -> None:
    path.write_text(text.rstrip() + "\n")


def archive(records: list[dict], destination: Path, manifest: dict, root_name: str) -> dict:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        raise FileExistsError(destination)
    manifest_bytes = (json.dumps(manifest, ensure_ascii=False, indent=2) + "\n").encode()
    expected = {record["archive_path"]: (record["bytes"], record["sha256"]) for record in records}
    with tarfile.open(destination, "w:gz", compresslevel=6) as tar:
        for record in records:
            source = safe(Path(record["source_path"]))
            tar.add(source, arcname=f"{root_name}/{record['archive_path']}", recursive=False)
        info = tarfile.TarInfo(f"{root_name}/PACKAGE_MANIFEST.json")
        info.size = len(manifest_bytes)
        tar.addfile(info, io.BytesIO(manifest_bytes))

    observed: dict[str, tuple[int, str]] = {}
    with tarfile.open(destination, "r:gz") as tar:
        for member in tar:
            if not member.isfile():
                raise ValueError(f"archive contains non-file member: {member.name}")
            if member.name == f"{root_name}/PACKAGE_MANIFEST.json":
                continue
            relative = member.name.split("/", 1)[1]
            stream = tar.extractfile(member)
            digest = hashlib.sha256()
            count = 0
            assert stream is not None
            for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
                count += len(block)
                digest.update(block)
            observed[relative] = (count, digest.hexdigest())
    if observed != expected:
        raise ValueError("archive readback differs from package manifest")
    return {
        "path": str(destination),
        "bytes": destination.stat().st_size,
        "sha256": sha256(destination),
        "payload_files": len(records),
        "payload_bytes": sum(record["bytes"] for record in records),
        "limit_bytes": LIMIT,
        "under_limit": destination.stat().st_size < LIMIT,
        "readback_verified": True,
    }


def build() -> dict:
    if not RUN.is_dir():
        raise FileNotFoundError(RUN)
    DELIVERY.mkdir(parents=True, exist_ok=True)
    data_records_, omitted = data_records()
    readme = DELIVERY / "README.md"
    write_text(readme, f"""# MMDD S2-COL-R2 交付包（{TAG}）

本目录包含两个 gzip 压缩包：

- `MMDD_S2_COL_R2_experiment_data_reports_{TAG}.tar.gz`：S2-COL-R2 最终报告、Phase A 诊断、六个实验臂的 dev/test 指标与逐 pair 预测、训练历史与 checkpoint 元数据、分析/审计回执、冻结自然训练语料、成本明细，以及运行时源码快照 `RUNTIME_SOURCE/`。
- `MMDD_src_S2_COL_R2_{TAG}.tar.gz`：仓库 `src/` 源代码快照（排除 `__pycache__` 和 `.pyc`）。

两个包都经过逐文件 SHA-256 回读校验；单包及两包合计均小于 300,000,000 bytes。

为满足上限，三类大体积产物没有复制进包：`FEATURES/` 特征缓存（9.8GB）、`FEATURE_INDEX/` 索引（177MB）、`NATURAL_TRAIN/natural_train_T0_pairs.sqlite`（960MB），以及全部模型权重 `checkpoints/**/*.pt`。省略项及原始大小记录在 `OMITTED_ARTIFACTS.json` 中，原始文件仍保留在服务器实验目录。

模型权重虽然不在包内，但每个 checkpoint 的 `MANIFEST.json`、`history.json` 与 `FEATURES.json` 均已保留：逐 epoch 的 dev 选型轨迹、`initial_parameter_sha256`、`selected_sha256`、`selected_epoch` 和特征身份哈希都在其中。`FINAL_REPORT.zh-CN.md` 的结论可直接对照这些回执复核。

`PACKAGE_VERIFICATION.json` 和 `SHA256SUMS` 是本目录的外部校验回执。""")
    omitted_path = DELIVERY / "OMITTED_ARTIFACTS.json"
    write_json(omitted_path, {"run": str(RUN), "omitted": omitted, "reason": "300MB delivery limit; original artifacts remain in place"})

    data_records_.extend([
        copy_record(readme, "README.md"),
        copy_record(omitted_path, "OMITTED_ARTIFACTS.json"),
    ])
    data_manifest = {
        "format_version": 1,
        "scope": "S2-COL-R2 experiment data and reports, size-bounded delivery",
        "source_run": str(RUN),
        "maximum_archive_bytes": LIMIT,
        "included_files": data_records_,
        "omitted_artifacts": omitted,
    }
    data_archive = DELIVERY / f"MMDD_S2_COL_R2_experiment_data_reports_{TAG}.tar.gz"
    data_receipt = archive(data_records_, data_archive, data_manifest, f"MMDD_S2_COL_R2_DATA_{TAG}")

    source_records: list[dict] = []
    for path in sorted((ROOT / "src").rglob("*")):
        if not path.is_file() or path.suffix == ".pyc" or "__pycache__" in path.parts:
            continue
        if ".env.openai" in path.parts:
            continue
        source_records.append(copy_record(path, f"src/{path.relative_to(ROOT / 'src')}"))
    source_scope = DELIVERY / "SOURCE_SCOPE.md"
    write_text(source_scope, """# Source snapshot

This archive contains the repository `src/` tree as plain source files. Python bytecode and `__pycache__` directories are excluded.

The snapshot is the working tree, not a commit: the S2-COL-R2 implementation (`mmdd_stage2/column_r2_*.py`, `run_stage2_columns_r2.py`) is present here in the same uncommitted state as on disk. `RUNTIME_SOURCE/` inside the data archive holds the separately frozen runtime modules that the S2-COL-R2 runs actually executed against.""")
    source_records.append(copy_record(source_scope, "SOURCE_SCOPE.md"))
    source_manifest = {
        "format_version": 1,
        "scope": "repository src snapshot",
        "source_root": str(ROOT / "src"),
        "included_files": source_records,
    }
    source_archive = DELIVERY / f"MMDD_src_S2_COL_R2_{TAG}.tar.gz"
    source_receipt = archive(source_records, source_archive, source_manifest, f"MMDD_SRC_S2_COL_R2_{TAG}")

    combined = data_receipt["bytes"] + source_receipt["bytes"]
    if data_receipt["bytes"] >= LIMIT or source_receipt["bytes"] >= LIMIT or combined >= LIMIT:
        raise ValueError(f"delivery exceeds 300MB: data={data_receipt['bytes']} source={source_receipt['bytes']} combined={combined}")
    verification = {
        "status": "verified",
        "maximum_bytes": LIMIT,
        "archives": [data_receipt, source_receipt],
        "combined_archive_bytes": combined,
        "combined_under_limit": True,
        "run": str(RUN),
    }
    write_json(DELIVERY / "PACKAGE_VERIFICATION.json", verification)
    (DELIVERY / "SHA256SUMS").write_text(
        f"{data_receipt['sha256']}  {Path(data_receipt['path']).name}\n"
        f"{source_receipt['sha256']}  {Path(source_receipt['path']).name}\n"
    )
    return verification


if __name__ == "__main__":
    print(json.dumps(build(), ensure_ascii=False, indent=2))
