"""Freeze the shared modern C1 base/closure schedules for B2 and B3.

This preparation is CPU/ANN-only.  B2 and B3 deliberately reuse the same
sampled batches and raw-Qwen hard-negative results; B3 applies positive
closure to the already materialized B2 rows without another ANN query.
"""
from __future__ import annotations

import argparse
import gzip
import json
import random
from collections import Counter
from pathlib import Path

from mmdd_stage1.artifacts import checkpoint_fingerprint
from mmdd_stage1.data import load_edge_examples
from mmdd_stage1.features import FeatureStore
from mmdd_stage1.retrieval import RawEmbeddingANNIndices
from mmdd_stage1.scoring import edge_positive_key, global_edge_positive_ids
from mmdd_stage1.training import sample_mixed_epoch
from prepare_stage1_r12_candidates import apply_positive_closure, materialize_batch
from run_stage1_bridge import OUT, R12, R25, ROOT, SEEDS, stable_sha, write_json


def _write_batches(path: Path, batches: list[list[dict]]) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(path, "wt", encoding="utf-8") as handle:
        for step, examples in enumerate(batches, 1):
            handle.write(json.dumps({"step": step, "epoch": 0, "batch_in_epoch": step,
                                     "examples": examples}, ensure_ascii=False) + "\n")
    return checkpoint_fingerprint(path)


def _stats(batches: list[list[dict]]) -> dict:
    rows = [row for batch in batches for row in batch]
    relation = Counter(f"{row['source_type']}->{row['destination_type']}" for row in rows)
    return {"batches": len(batches), "lists": len(rows), "relations": dict(sorted(relation.items())),
            "query_order_sha256": stable_sha([row["query_id"] for row in rows]),
            "candidate_membership_sha256": stable_sha([[row["query_id"], row["candidate_ids"]] for row in rows]),
            "positive_membership_sha256": stable_sha([[row["query_id"], row.get("positive_ids", [])] for row in rows])}


def prepare(seed: int, *, steps: int = 659) -> dict:
    if seed not in SEEDS:
        raise ValueError(seed)
    destination = OUT / "schedules" / f"seed{seed}_steps{steps}"
    manifest = destination / "SCHEDULE_MANIFEST.json"
    if manifest.is_file():
        return json.loads(manifest.read_text(encoding="utf-8"))
    train_path = R12 / "taskA_correctness/supervision/edge_lists.train_fit.jsonl"
    feature_root = ROOT / "work/stage1_optimization_r10_20260907/features_qwen3_vl_embedding_8b"
    corpus_path = ROOT / "work/stage1_optimization_r10_20260907/stage1_data/stage1_corpus.jsonl"
    raw_index_path = R25 / "common/raw_qwen_index"
    examples = load_edge_examples(train_path, split="train")
    sampled, _ = sample_mixed_epoch(examples, (), random.Random(seed), hard_fraction=0.5, dataset_sampling_alpha=0)
    sampled = sampled[: steps * 64]
    batches = [sampled[start:start + 64] for start in range(0, len(sampled), 64)]
    store = FeatureStore.from_path(feature_root, cache_size=40_000)
    indices = RawEmbeddingANNIndices(store, raw_index_path, corpus_sha256=checkpoint_fingerprint(corpus_path))
    known = global_edge_positive_ids(examples)
    requests = sorted({edge_positive_key(row) for row in sampled})
    ann_hits = {}
    for destination_type in ("table", "text", "image"):
        keys = [key for key in requests if key[2] == destination_type]
        for start in range(0, len(keys), 256):
            chunk = keys[start:start + 256]
            ann_hits.update(zip(chunk, indices.search_many([key[0] for key in chunk], destination_type, 256)))
            if start == 0 or start + 256 >= len(keys):
                print(json.dumps({"event": "bridge_ann", "seed": seed, "destination": destination_type,
                                  "completed": min(start + 256, len(keys)), "total": len(keys)}, ensure_ascii=False), flush=True)
    base_batches, closure_batches = [], []
    closure_audit = Counter()
    for step, batch in enumerate(batches, 1):
        materialized = materialize_batch(batch, known, ann_hits, seed, 0, step, enforce_positive_closure=False)
        base_rows = materialized["base"]
        # Keep the B2 base candidate IDs/order while carrying the actual
        # hard-negative provenance generated by the modern candidate arm.
        # These fields are receipt metadata; EdgeExample training consumes the
        # IDs and masks below, not the raw-ANN counters.
        for base_row, candidate_row in zip(base_rows, materialized["candidates"]):
            base_row["raw_ann_negative_quota"] = candidate_row["raw_ann_negative_quota"]
            base_row["raw_ann_negatives_used"] = candidate_row["raw_ann_negatives_used"]
        closed_rows, audit = apply_positive_closure(base_rows, known)
        closure_audit.update(audit)
        base_batches.append(base_rows)
        closure_batches.append(closed_rows)
    destination.mkdir(parents=True, exist_ok=True)
    files = {}
    for name, values in (("base_full", base_batches), ("closure_full", closure_batches),
                         ("base_first356", base_batches[:356]), ("closure_first356", closure_batches[:356])):
        path = destination / f"{name}.jsonl.gz"
        files[name] = {"path": str(path.resolve()), "sha256": _write_batches(path, values), "stats": _stats(values)}
    payload = {"status": "complete", "seed": seed, "steps": len(batches), "batch_size": 64,
               "source_sampling": "R25 sample_mixed_epoch; raw-Qwen ANN hard negatives; closure off then applied offline",
               "train_input": {"path": str(train_path.resolve()), "sha256": checkpoint_fingerprint(train_path)},
               "raw_index": {"path": str(raw_index_path.resolve()), "manifest_sha256": checkpoint_fingerprint(raw_index_path / "manifest.json")},
               "files": files, "closure_audit": dict(closure_audit),
               "shared_base_identity": files["base_full"]["sha256"],
               "code_sha256": checkpoint_fingerprint(Path(__file__))}
    write_json(manifest, payload)
    return payload


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", action="append", type=int, choices=SEEDS)
    parser.add_argument("--steps", type=int, default=659)
    args = parser.parse_args()
    for seed in args.seed or list(SEEDS):
        print(json.dumps(prepare(seed, steps=args.steps), ensure_ascii=False, indent=2))
